insert into customers(name, email, address) values ("Marnie Mccrory", "denessa_osunabs@triumph.an", "Strikes Road 2209, Mariah Hill, Kyrgyzstan, 902644");
insert into customers(name, email, address) values ("Fuller Blanch", "markina_gilyarda@differential.uqf", "Valley St 9999, Abilene, Romania, 931379");
insert into customers(name, email, address) values ("Maheen Geis", "sarde_visserc@economies.upx", "Lands Road 2713, La Libertad, Japan, 386999");
insert into customers(name, email, address) values ("Bryden Kleckner", "arek_cataldozx8@strategies.jqs", "Ferry St 663, West Glacier, Slovenia, 936059");
insert into customers(name, email, address) values ("Cristyn Reyna", "tong_fitchoas@suffering.ks", "Thermal Street 9752, Balfour, Ghana, 578283");
insert into customers(name, email, address) values ("Kellisha Ratner", "omara_ankneyp@happen.vy", "Motherboard St 5921, Aalen, Slovakia, 415161");
insert into customers(name, email, address) values ("Genevieve Barringer", "shayla_mcquaidr5@associations.ld", "Necessity Road 9370, Arthur City, Hungary, 972981");
insert into customers(name, email, address) values ("Megha Reeve", "staley_birdsall3x@scotland.zk", "Easy Street 9209, Port Gibson, Papua New Guinea, 269783");
insert into customers(name, email, address) values ("Bambie Basso", "davalyn_reisingeroap@concentrate.wy", "Examinations Street 4048, Iquitos, Bermuda, 414818");
insert into customers(name, email, address) values ("Shawnta Daub", "amari_calleam@define.mi", "Icon Street 8232, Ohi, Burma, 909674");
